// 二段階認証（TOTP）のテスト用の部品。
//   ・totp()          … RFC 6238 の 6 桁。認証アプリの代わり（QR から取り出した secret で計算する）
//   ・makeFakeGoTrue() … Supabase Auth（GoTrue）の登録・確認の模擬。**実物の応答の形**で返す:
//                        qr_code は生の SVG 文字列（data: の付かない形。公式クライアントだけが付ける）、
//                        uri は otpauth://totp/{issuer}:{account}?algorithm=SHA1&digits=6&issuer=…&period=30&secret=…
//                        登録のたびに、新しい秘密鍵を発行する（同じ鍵を使い回さない）
import { createHmac, randomBytes } from "node:crypto";

const B32 = "ABCDEFGHIJKLMNOPQRSTUVWXYZ234567";

export function base32Encode(buf) {
  let bits = 0, value = 0, out = "";
  for (const byte of buf) {
    value = (value << 8) | byte; bits += 8;
    while (bits >= 5) { out += B32[(value >>> (bits - 5)) & 31]; bits -= 5; }
  }
  if (bits > 0) out += B32[(value << (5 - bits)) & 31];
  return out;
}

export function base32Decode(s) {
  const clean = String(s).replace(/=+$/, "").replace(/\s+/g, "").toUpperCase();
  let bits = 0, value = 0;
  const out = [];
  for (const ch of clean) {
    const i = B32.indexOf(ch);
    if (i < 0) throw new Error("base32 の文字ではありません");
    value = (value << 5) | i; bits += 5;
    if (bits >= 8) { out.push((value >>> (bits - 8)) & 255); bits -= 8; }
  }
  return Buffer.from(out);
}

/** RFC 6238（HMAC-SHA1）。atMs は UNIX ミリ秒 */
export function totp(secretBase32, atMs = Date.now(), { digits = 6, period = 30 } = {}) {
  const counter = Math.floor(atMs / 1000 / period);
  const msg = Buffer.alloc(8);
  msg.writeBigUInt64BE(BigInt(counter));
  const h = createHmac("sha1", base32Decode(secretBase32)).update(msg).digest();
  const o = h[h.length - 1] & 0x0f;
  const bin = ((h[o] & 0x7f) << 24) | (h[o + 1] << 16) | (h[o + 2] << 8) | h[o + 3];
  return String(bin % 10 ** digits).padStart(digits, "0");
}

/** otpauth://totp/… の URI を分解する（形が違えば null）。秘密の情報を扱うので、ログには出さないこと */
export function parseOtpauth(uri) {
  const m = /^otpauth:\/\/totp\/([^?]*)\?(.*)$/i.exec(String(uri));
  if (!m) return null;
  const q = new URLSearchParams(m[2]);
  return { label: decodeURIComponent(m[1]), secret: q.get("secret"), issuer: q.get("issuer"), algorithm: q.get("algorithm"),
    digits: q.get("digits"), period: q.get("period") };
}

/** GoTrue が返す SVG に似た、生の SVG（xml 宣言つき）。中身は QR ではない。「渡していない」ことを見分ける目印を入れる */
export const RAW_QR_MARKER = "RAWSVG-FROM-GOTRUE";
const rawSvg = () => `<?xml version="1.0"?>\n<!-- Generated by SVGo -->\n<svg width="90" height="90" xmlns="http://www.w3.org/2000/svg"><!-- ${RAW_QR_MARKER} --><rect width="90" height="90" style="fill:white"/></svg>`;

/**
 * @param {{issuer?:string, account?:string, now?:()=>number}} opts
 *   issuer … GoTrue は、Site URL のホスト名（issuer を渡さないとき）
 */
export function makeFakeGoTrue({ issuer = "gw.8grp.co.jp", account = "taro@example.co.jp", now = () => Date.now() } = {}) {
  const st = { factors: new Map(), challenges: new Map(), calls: [], seq: 0, notEnabled: false, breakEnroll: null };

  const uriOf = (secret) => `otpauth://totp/${encodeURIComponent(issuer)}:${encodeURIComponent(account)}`
    + `?algorithm=SHA1&digits=6&issuer=${encodeURIComponent(issuer)}&period=30&secret=${secret}`;

  /** @returns {{status:number, body:object}} */
  function handle(method, path, body) {
    st.calls.push({ method, path });
    if (method === "POST" && path === "/factors") {
      if (st.notEnabled) return { status: 422, body: { code: 422, error_code: "mfa_totp_enroll_not_enabled", msg: "MFA enroll is disabled for TOTP" } };
      const secret = base32Encode(randomBytes(20));              // 新しい秘密鍵（160 bit）
      const id = `factor-${++st.seq}`;
      st.factors.set(id, { secret, status: "unverified" });
      const full = { id, type: "totp", friendly_name: body?.friendly_name || "", totp: { qr_code: rawSvg(), secret, uri: uriOf(secret) } };
      return { status: 200, body: st.breakEnroll ? st.breakEnroll(full) : full };
    }
    let m = /^\/factors\/([^/]+)\/challenge$/.exec(path);
    if (method === "POST" && m) {
      if (!st.factors.has(m[1])) return { status: 404, body: { code: 404, msg: "MFA factor not found" } };
      const cid = `challenge-${++st.seq}`;
      st.challenges.set(cid, m[1]);
      return { status: 200, body: { id: cid, type: "totp", expires_at: Math.floor(now() / 1000) + 300 } };
    }
    m = /^\/factors\/([^/]+)\/verify$/.exec(path);
    if (method === "POST" && m) {
      const f = st.factors.get(m[1]);
      if (!f || st.challenges.get(body?.challenge_id) !== m[1]) return { status: 400, body: { code: 400, msg: "MFA challenge could not be found" } };
      const t = now();
      const good = [-30000, 0, 30000].some((d) => totp(f.secret, t + d) === String(body?.code));
      if (!good) return { status: 400, body: { code: 400, error_code: "mfa_verification_failed", msg: "Invalid TOTP code entered" } };
      f.status = "verified";
      return { status: 200, body: { access_token: "aal2-token", token_type: "bearer", expires_in: 3600, expires_at: Math.floor(t / 1000) + 3600, refresh_token: "r2", user: { id: "u1" } } };
    }
    return { status: 404, body: { msg: "not found" } };
  }
  const verified = () => [...st.factors.entries()].filter(([, f]) => f.status === "verified").map(([id]) => id);
  return { handle, st, verified };
}
